### ISSUE TITLE
Ability to place an image strictly under a heading

### ISSUE THREAD

**Issue by mohamed-riza** [khalid-hussain/IIUM-Thesis-LaTeX-Class#10]
Currently, the images move as per what may be best for the layout. Is it possible to fix it to one area, like underneath a particular heading?

**Comment by khalid-hussain** [comment]
Manually forcing the figures is not recommended. However, you could try the following: [How to control the position of floating images?](https://tex.stackexchange.com/questions/19766/how-to-control-the-position-of-floating-images)

You'll have to adapt the answer to fit your workflow. To call the `placeins` package, head to your YAML front matter (usually the first file of compilation) and follow the example as follows:

```yaml
---
title: The Big Data
author: Mohammad Khalid Hussain
date: 12 September 2017
header-includes:
  - \usepackage{placeins}
  - \usepackage{Other Package you might need in the future}
---
```

UPDATE: I realize this will not work due to the workflow I've set up. I've added the package to the thesis class. Please see commit 1df1597a34a0a105d7f11d57d2d8207c2ac2aaaa
